In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [2]:
edo = pd.read_csv(r'C:\KGR5\edogawa2017+cluster.csv', encoding = 'utf-8')

In [3]:
edo[0:10]

Unnamed: 0     地区  自転車盗数  住民数(合計)  住民数(男性)  住民数(女性)  人口密度\r\n[人/k㎡]  \
0           0   東小松川     32    11383     5814     5569    10045.005290   
1           1  西小松川町      3     3380     1764     1616     6452.844597   
2           2    小松川     40    16293     7852     8441     9531.414531   
3           3    西葛西    172    45320    22636    22684    22787.610620   
4           4    中葛西    137    38262    20003    18259    23319.112630   
5           5    北葛西     42    19816    10114     9702    11756.748740   
6           6    南葛西    113    34164    17521    16643    22611.688400   
7           7    東葛西    170    42692    22648    20044    15219.964350   
8           8     新堀      9     4576     2409     2167    13298.459750   
9           9    清新町     43    14339     6907     7432    14975.456920   

   面積[k㎡]    世帯数  クラスタ  
0  1.1332   5479     0  
1  0.5238   1596     0  
2  1.7094   7003     0  
3  1.9888  22369     1  
4  1.6408  21215     1  
5  1.6855   8997     0  
6  1.5109  15217     1  
7  2.8050  22872     1  
8  0.3441   1897     0  
9  0.9575   5988     0

In [4]:
edo_ = edo.drop(edo.columns[[0, 1, 2, 6, 7]], axis=1)

In [5]:
edo_[0:10]

住民数(合計)  住民数(男性)  住民数(女性)    世帯数  クラスタ
0    11383     5814     5569   5479     0
1     3380     1764     1616   1596     0
2    16293     7852     8441   7003     0
3    45320    22636    22684  22369     1
4    38262    20003    18259  21215     1
5    19816    10114     9702   8997     0
6    34164    17521    16643  15217     1
7    42692    22648    20044  22872     1
8     4576     2409     2167   1897     0
9    14339     6907     7432   5988     0

In [6]:
edo_np = edo_.values
edo_x = edo_np[:,0:3]
edo_y = edo_np[:,4]

In [7]:
edo_x[0:10]

array([[11383,  5814,  5569],
       [ 3380,  1764,  1616],
       [16293,  7852,  8441],
       [45320, 22636, 22684],
       [38262, 20003, 18259],
       [19816, 10114,  9702],
       [34164, 17521, 16643],
       [42692, 22648, 20044],
       [ 4576,  2409,  2167],
       [14339,  6907,  7432]], dtype=int64)

In [8]:
edo_y[0:10]

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 0], dtype=int64)

In [9]:
sc = StandardScaler()
edo_std = sc.fit_transform(edo_x)

C:\Users\kishi\Anaconda3\envs\edogawa\lib\site-packages\sklearn\utils\validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\kishi\Anaconda3\envs\edogawa\lib\site-packages\sklearn\utils\validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [10]:
edo_std[0:10]

array([[-0.35998832, -0.34732826, -0.37252144],
       [-1.03495828, -1.01830118, -1.05055328],
       [ 0.0541192 , -0.00968807,  0.12009364],
       [ 2.50224528,  2.43961158,  2.56310082],
       [ 1.90697626,  2.00339635,  1.80410996],
       [ 0.35124767,  0.36506273,  0.33638459],
       [ 1.56135251,  1.59219764,  1.52692821],
       [ 2.28060077,  2.44159964,  2.11027915],
       [-0.9340881 , -0.91144253, -0.95604391],
       [-0.11068041, -0.16624841, -0.05297343]])

In [11]:
clf = LogisticRegression()
edo_clf = clf.fit(edo_std, edo_y)

C:\Users\kishi\Anaconda3\envs\edogawa\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [12]:
edo_clf.intercept_

array([-1.39688541])

In [13]:
edo_clf.coef_

array([[0.68711821, 0.67399752, 0.69960658]])

In [14]:
edo_np = edo_.values
edo_x = edo_np[:,1:4]
edo_y = edo_np[:,4]
sc = StandardScaler()
edo_sc = sc.fit_transform(edo_x)
edo_std[0:10]
clf = LogisticRegression()
edo_clf = clf.fit(edo_std, edo_y)

C:\Users\kishi\Anaconda3\envs\edogawa\lib\site-packages\sklearn\utils\validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\kishi\Anaconda3\envs\edogawa\lib\site-packages\sklearn\utils\validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\kishi\Anaconda3\envs\edogawa\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [15]:
edo_clf.intercept_

array([-1.39688541])

In [16]:
edo_clf.coef_

array([[0.68711821, 0.67399752, 0.69960658]])