In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [2]:
edo = pd.read_csv(r'C:\KGR5\edogawa_kaneda.csv', encoding = 'cp932')

In [3]:
edo[0:10]

地区  クラスタ  自転車盗数  大学・短大（NAVITIME）  駅（NAVITIME）  工場  0～4歳  5～9歳  10～14歳  \
0   東小松川     0     32                0            0   0   517   498     491   
1  西小松川町     0      3                0            0   0   102   116     152   
2    小松川     0     40                0            0   0   707   869     907   
3    西葛西     1    172                0            1   0  1997  1909    1858   
4    中葛西     1    137                0            1   0  1771  1532    1405   
5    北葛西     0     42                0            0   0   953  1020     954   
6    南葛西     1    113                0            0   0  1868  1723    1824   
7    東葛西     1    170                0            0   0  1954  1706    1804   
8     新堀     0      9                0            0   0   218   313     297   
9    清新町     0     43                0            0   0   519   697     643   

   15～19歳   ...    民営の借家世帯数  給与住宅世帯数  間借り世帯数  一戸建世帯数  長屋建世帯数  共同住宅世帯数  １・２階建  \
0     555   ...        1959      120      57    2241      44     2617    720   
1     199   ...         370       23      22     727      14      552    194   
2     947   ...         485      118      45     328      25     6175     90   
3    2246   ...        9150      773     239    1411      35    18833   1223   
4    1870   ...       12701     1125     259    2609      93    17752   3243   
5    1033   ...        2809      425      74    2414      55     5835   1415   
6    1947   ...        6351      617     142    1696      94    12460   1279   
7    2308   ...       13411     1205     309    3908     119    17809   4679   
8     269   ...         647       12      16     737       8      989    321   
9     710   ...         303       90      28      38      21     5472      1   

   ３～５階建  ６～10階建  11階建以上  
0   1246     443     208  
1    190      70      98  
2    449     407    5229  
3   3803    6832    6975  
4   6430    5294    2785  
5   1285    1687    1448  
6   2875    4732    3574  
7   5838    5176    2116  
8    327     264      77  
9    830     820    3821  

[10 rows x 72 columns]

In [4]:
edo_ = edo.drop(edo.columns[[0, 2]], axis=1)

In [5]:
edo_[0:10]

クラスタ  大学・短大（NAVITIME）  駅（NAVITIME）  工場  0～4歳  5～9歳  10～14歳  15～19歳  20～24歳  \
0     0                0            0   0   517   498     491     555     613   
1     0                0            0   0   102   116     152     199     182   
2     0                0            0   0   707   869     907     947     785   
3     1                0            1   0  1997  1909    1858    2246    2825   
4     1                0            1   0  1771  1532    1405    1870    3106   
5     0                0            0   0   953  1020     954    1033     951   
6     1                0            0   0  1868  1723    1824    1947    2198   
7     1                0            0   0  1954  1706    1804    2308    3376   
8     0                0            0   0   218   313     297     269     253   
9     0                0            0   0   519   697     643     710     635   

   25～29歳   ...    民営の借家世帯数  給与住宅世帯数  間借り世帯数  一戸建世帯数  長屋建世帯数  共同住宅世帯数  １・２階建  \
0     711   ...        1959      120      57    2241      44     2617    720   
1     172   ...         370       23      22     727      14      552    194   
2     675   ...         485      118      45     328      25     6175     90   
3    3091   ...        9150      773     239    1411      35    18833   1223   
4    3519   ...       12701     1125     259    2609      93    17752   3243   
5    1036   ...        2809      425      74    2414      55     5835   1415   
6    2230   ...        6351      617     142    1696      94    12460   1279   
7    3917   ...       13411     1205     309    3908     119    17809   4679   
8     209   ...         647       12      16     737       8      989    321   
9     687   ...         303       90      28      38      21     5472      1   

   ３～５階建  ６～10階建  11階建以上  
0   1246     443     208  
1    190      70      98  
2    449     407    5229  
3   3803    6832    6975  
4   6430    5294    2785  
5   1285    1687    1448  
6   2875    4732    3574  
7   5838    5176    2116  
8    327     264      77  
9    830     820    3821  

[10 rows x 70 columns]

#大学・駅・工場で分析

In [6]:
edo_np = edo_.values
edo_x = edo_np[:,1:4]
edo_y = edo_np[:,0]
sc = StandardScaler()
edo_std = sc.fit_transform(edo_x)
clf = LogisticRegression()
edo_clf = clf.fit(edo_std, edo_y)

C:\Users\kishi\Anaconda3\envs\edogawa\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [7]:
edo_clf.intercept_

array([-1.13078025])

In [8]:
edo_clf.coef_

array([[0.76655651, 1.12794224, 0.        ]])

In [9]:
#年代別に分析

In [10]:
edo_x = edo_np[:,4:21]
sc = StandardScaler()
edo_std = sc.fit_transform(edo_x)
clf = LogisticRegression()
edo_clf = clf.fit(edo_std, edo_y)

C:\Users\kishi\Anaconda3\envs\edogawa\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [11]:
edo_clf.intercept_

array([-1.21977323])

In [12]:
edo_clf.coef_

array([[ 0.2026085 , -0.26801757, -0.44080257, -0.18207443,  0.59112759,
         0.96520305,  0.75903849,  0.71272081,  0.42647205,  0.39036116,
         0.20823562,  0.03387837, -0.20316843, -0.16867732,  0.01639694,
        -0.12994534, -0.49303613]])

#世帯人数やその構成

In [13]:
edo_x = edo_np[:,22:34]
sc = StandardScaler()
edo_std = sc.fit_transform(edo_x)
clf = LogisticRegression()
edo_clf = clf.fit(edo_std, edo_y)

C:\Users\kishi\Anaconda3\envs\edogawa\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [14]:
edo_clf.intercept_

array([-1.09458819])

In [15]:
edo_clf.coef_

array([[ 1.03347898,  0.45646479,  0.1735211 ,  0.18195321, -0.07208963,
        -0.23802164, -0.03391384,  0.03825293,  0.62645409,  0.2856503 ,
         1.03347898, -0.43564625]])

#業種別

In [16]:
edo_x = edo_np[:,35:58]
sc = StandardScaler()
edo_std = sc.fit_transform(edo_x)
clf = LogisticRegression()
edo_clf = clf.fit(edo_std, edo_y)

C:\Users\kishi\Anaconda3\envs\edogawa\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [17]:
edo_clf.intercept_

array([-1.25809215])

In [18]:
edo_clf.coef_

array([[-0.17375126, -0.21636327,  0.19186725,  0.02136971,  0.14944503,
        -0.47859427,  0.94790225,  0.01470429,  0.23974907,  0.46532011,
         0.75320392,  0.41467089, -0.06462415,  0.30045361, -0.31173266,
        -0.12279474, -0.01030614,  0.23701919, -0.14417615,  0.82603422,
        -0.37820573, -0.14081417, -0.00518269]])

#住居のタイプ

In [19]:
edo_x = edo_np[:,58:66]
sc = StandardScaler()
edo_std = sc.fit_transform(edo_x)
clf = LogisticRegression()
edo_clf = clf.fit(edo_std, edo_y)

C:\Users\kishi\Anaconda3\envs\edogawa\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [20]:
edo_clf.intercept_

array([-1.06086377])

In [21]:
edo_clf.coef_

array([[ 0.20175303, -0.21772962,  1.36525678,  0.5459503 ,  0.20286189,
        -0.45450783,  0.08876926,  1.11855994]])

#住居の階数

In [22]:
edo_x = edo_np[:,66:70]
sc = StandardScaler()
edo_std = sc.fit_transform(edo_x)
clf = LogisticRegression()
edo_clf = clf.fit(edo_std, edo_y)

C:\Users\kishi\Anaconda3\envs\edogawa\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [23]:
edo_clf.intercept_

array([-1.19518423])

In [24]:
edo_clf.coef_

array([[0.70855112, 1.0942821 , 0.98090543, 0.35620015]])