In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [2]:
edo = pd.read_csv(r'C:\KGR5\edogawa_kurokawa.csv', encoding = 'cp932')

In [3]:
edo[0:10]

地区  クラスタ  自転車盗数  区立自転車駐車場設置状況  自転車駐輪場一覧(NAVITIME)  使用料制駐輪場  \
0   東小松川     0     32             0                   0        0   
1  西小松川町     0      3             0                   0        0   
2    小松川     0     40             0                   1        0   
3    西葛西     1    172             5                   4        0   
4    中葛西     1    137             3                   1        0   
5    北葛西     0     42             0                   0        0   
6    南葛西     1    113             0                   0        0   
7    東葛西     1    170             0                   3        0   
8     新堀     0      9             0                   0        0   
9    清新町     0     43             0                   0        0   

   駐輪場(Google map)  公園(Google map)  
0                0               4  
1                0               3  
2                1               9  
3                4               9  
4                1               4  
5                0               9  
6                1              14  
7                2               5  
8                0               5  
9                0               7

In [4]:
edo_ = edo.drop(edo.columns[[0, 2]], axis=1)

In [5]:
edo_[0:10]

クラスタ  区立自転車駐車場設置状況  自転車駐輪場一覧(NAVITIME)  使用料制駐輪場  駐輪場(Google map)  \
0     0             0                   0        0                0   
1     0             0                   0        0                0   
2     0             0                   1        0                1   
3     1             5                   4        0                4   
4     1             3                   1        0                1   
5     0             0                   0        0                0   
6     1             0                   0        0                1   
7     1             0                   3        0                2   
8     0             0                   0        0                0   
9     0             0                   0        0                0   

   公園(Google map)  
0               4  
1               3  
2               9  
3               9  
4               4  
5               9  
6              14  
7               5  
8               5  
9               7

In [6]:
edo_np = edo_.values
edo_x = edo_np[:,1:7]
edo_y = edo_np[:,0]

In [7]:
edo_x[0:10]

array([[ 0,  0,  0,  0,  4],
       [ 0,  0,  0,  0,  3],
       [ 0,  1,  0,  1,  9],
       [ 5,  4,  0,  4,  9],
       [ 3,  1,  0,  1,  4],
       [ 0,  0,  0,  0,  9],
       [ 0,  0,  0,  1, 14],
       [ 0,  3,  0,  2,  5],
       [ 0,  0,  0,  0,  5],
       [ 0,  0,  0,  0,  7]], dtype=int64)

In [8]:
edo_y[0:10]

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 0], dtype=int64)

In [9]:
sc = StandardScaler()
edo_std = sc.fit_transform(edo_x)

C:\Users\kishi\Anaconda3\envs\edogawa\lib\site-packages\sklearn\utils\validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\kishi\Anaconda3\envs\edogawa\lib\site-packages\sklearn\utils\validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [10]:
edo_std[0:10]

array([[-0.50709255, -0.47837459,  0.        , -0.47663171, -0.33936388],
       [-0.50709255, -0.47837459,  0.        , -0.47663171, -0.60132898],
       [-0.50709255, -0.07359609,  0.        ,  0.01108446,  0.97046162],
       [ 2.35342954,  1.14073941,  0.        ,  1.47423296,  0.97046162],
       [ 1.2092207 , -0.07359609,  0.        ,  0.01108446, -0.33936388],
       [-0.50709255, -0.47837459,  0.        , -0.47663171,  0.97046162],
       [-0.50709255, -0.47837459,  0.        ,  0.01108446,  2.28028712],
       [-0.50709255,  0.73596091,  0.        ,  0.49880063, -0.07739878],
       [-0.50709255, -0.47837459,  0.        , -0.47663171, -0.07739878],
       [-0.50709255, -0.47837459,  0.        , -0.47663171,  0.44653142]])

In [11]:
clf = LogisticRegression()
edo_clf = clf.fit(edo_std, edo_y)

C:\Users\kishi\Anaconda3\envs\edogawa\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [12]:
edo_clf.intercept_

array([-1.18869357])

In [13]:
edo_clf.coef_

array([[0.32423753, 1.26704889, 0.        , 0.62411741, 0.58766382]])